- include: bootstrap.yaml
- include: raid_and_lvm.yaml

#- include: root-device.yaml
#- include: parted.yaml
#  tags:
#  - parted
- include: download.yaml
  when: "{{ image.disk_format != 'raw' }}"
- include: write.yaml
- include: grub.yaml
#  tags:
#  - parted
